### ISSUE TITLE
Give your feedback!

### ISSUE THREAD

**Issue by FBoucher** [microsoft/AzUrlShortener#122]
Hello!
I would love to have your feedback...
Did you try the AzUrlShortener? Did you like it?
It gave you some ideas....

Leave a comment!

┆Issue is synchronized with this [Trello card](https://trello.com/c/AXDK4nr8) by [Unito](https://www.unito.io)

**Comment by kilakewe** [comment]
It was delightfully simple and easy to setup.

**Comment by fs366e2spm** [comment]
Sure I tried it :-), not only trying. I'm using it and assigned a own domain name.

Like the project and the functionality, "easy" parts on Azure and very low costs. Also good to learn the Azure components and get some more/new insights.

Looked before for an own solution but found only PHP or other functionality which somehow required to have on own server or hosting it somewhere.

**Comment by Lukas34** [comment]
What an amazing project ❤
Although in its early stages, it works very well and I love the serverless nature of it.

Maybe you should also mention that to add a custom domain you not only need to add it as an app service domain but also change the `AzFunctionUrl` in the app settings of the admin/web interface so that the copy button uses your custom domain.
