### ISSUE TITLE
On mobile devices the redirects don't work every time

### ISSUE THREAD

**Issue by kitzler-walli** [microsoft/AzUrlShortener#521]
Currently I try to analyse an issue where mobile devices scan the qr code but then only a white page is displayed in the browser.
The browser shows the correct url and reloading the page usually causes the redirect.

Has anyone experienced something similar?
We're using a custom domain for the shortener but in 90% of all redirects it works just fine.
Debugging the response is challenging as is happens not every time and never happened on a full client.

**Comment by workmail20** [comment]
Maybe you have a bad internet connection? I think only 95% of your redirects will be successful; the others will be broken due to internet communication errors/pings/timings. The application uses a simple 302 header for redirects. It's very robust, unlike meta/js headers.

I plan to research source codes in the next few days. They need to be checked.

**Comment by kitzler-walli** [comment]
Not necessary - my problems resulted from slow container start times in Azure. Case closed, sorry for not updating the issue.

**Comment by blitzmann** [comment]
@kitzler-walli if issue has been resolved and isn't an issue regarding the project here, please close the issue
